blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/wouterfennis/omp-travel-time/security/advisories
    about: Please report security vulnerabilities privately.
